version: '3'
services:
  book_catalog:
    image: $CONTAINER_REGISTRY.azurecr.io/book_catalog:$VERSION
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "4001:5000"
    environment:
      - DATABASE_URL=postgresql://sumedhpart5_user:4YSRqUaWffzs1Wz5NO2zthypKg6zrwwW@dpg-crfatsbgbbvc73c1kbo0-a.oregon-postgres.render.com/sumedhpart5
    restart: "no"

  inventory_management:
    image: $CONTAINER_REGISTRY.azurecr.io/inventory_management:$VERSION
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "4002:5001"
    environment:
      - DATABASE_URL=postgresql://sumedhpart5_user:4YSRqUaWffzs1Wz5NO2zthypKg6zrwwW@dpg-crfatsbgbbvc73c1kbo0-a.oregon-postgres.render.com/sumedhpart5
    restart: "no"