apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/book_catalog:$VERSION
 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://sumedhpart5_user:4YSRqUaWffzs1Wz5NO2zthypKg6zrwwW@dpg-crfatsbgbbvc73c1kbo0-a.oregon-postgres.render.com/sumedhpart5


---


apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: 5000



---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/inventory_management:$VERSION
 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: postgresql://sumedhpart5_user:4YSRqUaWffzs1Wz5NO2zthypKg6zrwwW@dpg-crfatsbgbbvc73c1kbo0-a.oregon-postgres.render.com/sumedhpart5


---


apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 4002
      targetPort: 5001
 